### ISSUE TITLE
Add Semigroup instance

### ISSUE THREAD

**Issue by ricksanchez** [psibi/fakedata#11]
It can be very nice to be able to write code like this:
`Pokemon.names <> pure "_" <> Pokemon.names <> pure "@mail.com"`

This is the desired instance we should implement:
`instance Semigroup a => Semigroup (Fake a)`

Maybe also `Monoid` instance can be useful for some.

**Comment by psibi** [comment]
Sounds reasonable. Can you send a MR for it ? If not, I will see if I can get back to this on the coming weekend.

**Comment by ricksanchez** [comment]
sure, I will

**Comment by psibi** [comment]
Fixed via https://github.com/psibi/fakedata/pull/12 . Thanks @ricksanchez
