### ISSUE TITLE
InvalidField when generating Job Title

### ISSUE THREAD

**Issue by danwdart** [psibi/fakedata#4]
```
λ> import Faker
λ> import qualified Faker.Job as FJ
λ> generate FJ.title
*** Exception: InvalidField "job" "field"
```
gives `*** Exception: InvalidField "job" "field"`
```

**Comment by psibi** [comment]
@danwdart Thanks for the bug report. This should be fixed in the `bench` branch: https://github.com/psibi/fakedata/tree/bench

```
λ> import Faker
λ> import qualified Faker.Job as FJ
λ> generate FJ.title
"Regional Engineer"
```

I will make a new release in a couple of days, meanwhile you can use that branch. It contains various other fixes and huge perf improvments.

**Comment by danwdart** [comment]
Oh, lovely. Thanks!

**Comment by psibi** [comment]
I think we can keep the issue open until I make an hackage release. Thanks!

**Comment by danwdart** [comment]
Oh, fair enough, yeah

**Comment by psibi** [comment]
A new version has been uploaded to Hackage. Thanks!
